version: '3'

services:
  node:
    image : node:10
    working_dir : "/app"
    volumes:
        - .:/app
    ports:
      - '3000:3000'
    command : ['npm', 'start']
    links:
      - mongo
    environment:
      APP_PORT: 3000

  mongo:
    image: mongo
    ports:
      - '27019:27017'
